name: CI

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

on:
  push:

env:
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.cache/ms-playwright
  VITEST_GENERATE_UI_TOKEN: 'true'

jobs:
  test-browser:
    name: 'Browsers: node-20, ${{ matrix.os }}'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - macos-latest
          - windows-latest
      fail-fast: false

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup-and-cache
        with:
          node-version: 20

      - uses: browser-actions/setup-chrome@b94431e051d1c52dcbe9a7092a4f10f827795416 # v2.1.0
      - uses: browser-actions/setup-firefox@5914774dda97099441f02628f8d46411fcfbd208 # v1.7.0

      - name: Install
        run: pnpm i

      - name: Install Playwright Dependencies
        run: pnpm exec playwright install --with-deps --only-shell

      - name: Build
        run: pnpm run build

      - name: Test Browser (webdriverio)
        run: pnpm run test:browser:webdriverio
